import { siteConfig } from "./site-config";
export type SeoPage={slug:string;title:string;description:string;intro:string;sections:{heading:string;body:string;bullets?:string[]}[];faqs?:{question:string;answer:string}[]};
const pages: SeoPage[]=[
{slug:"restaurant-management-system",title:"Restaurant Management System",description:"RESTRA is a restaurant management system for restaurants, cafés, and cloud kitchens, with POS, ordering, inventory, kitchen workflows, and reporting.",intro:"RESTRA is a Restaurant Management System that brings POS, billing, order management, QR ordering, inventory, kitchen workflows, staff permissions, table management, and reporting into one platform.",sections:[{heading:"Who RESTRA is for",body:"RESTRA is built for restaurants, cafés, and cloud kitchens that need one connected system for day-to-day operations."},{heading:"What RESTRA helps manage",body:"The platform connects the flow from a customer order to kitchen preparation, billing, inventory updates, and manager visibility.",bullets:["Restaurant POS and billing","Dine-in and table workflows","QR ordering","Kitchen order tracking","Inventory and ingredient monitoring","Staff roles and permissions","Reports and analytics"]},{heading:"How RESTRA works",body:"A typical workflow starts with an order, sends it into the kitchen, tracks preparation status, generates a bill, updates operational records, and gives managers a view of the day’s activity."}],faqs:[{question:"What is RESTRA?",answer:"RESTRA is a Restaurant Management System for restaurants, cafés, and cloud kitchens. It combines POS, billing, ordering, inventory, kitchen workflows, staff permissions, table management, and reporting."},{question:"What is RESTRA used for?",answer:"RESTRA is used to manage restaurant sales, orders, billing, QR ordering, kitchen preparation, inventory, staff access, table activity, and operational reporting in one platform."},{question:"Is RESTRA available in Nepal?",answer:"RESTRA’s public website positions the product for the Nepal market. Contact the RESTRA team to confirm current availability and onboarding details."}]},
{slug:"pos",title:"Restaurant POS System",description:"Use RESTRA as a restaurant POS system for sales, billing, and connected order workflows.",intro:"RESTRA’s point-of-sale workflow brings restaurant sales and billing into the same system as orders, kitchen preparation, and operational reporting.",sections:[{heading:"What the POS workflow covers",body:"Teams can handle restaurant sales and transactions from a centralized point of sale, then follow the order through preparation and completion.",bullets:["Centralized restaurant sales and transactions","Accurate bill generation and printing","Order status visibility from placement to completion"]},{heading:"Who it is for",body:"The POS workflow is designed for restaurants, cafés, and cloud kitchens that want order and billing activity connected in one operational system."}]},
{slug:"inventory",title:"Restaurant Inventory Management",description:"Track restaurant inventory and ingredients with RESTRA’s connected stock management workflow.",intro:"RESTRA helps restaurant teams monitor ingredients, record stock movement, and identify low-stock items before service is affected.",sections:[{heading:"What inventory management covers",body:"The inventory workflow gives teams visibility into what is moving in and out of the kitchen and highlights items that need attention.",bullets:["Track ingredient stock levels","Log new inventory items","Receive low-stock alerts","See inventory movement alongside restaurant operations"]},{heading:"Why it matters",body:"Connecting inventory with orders and billing helps teams maintain a clearer operational picture instead of relying on disconnected records."}]},
{slug:"kitchen-display-system",title:"Kitchen Display System Workflow",description:"Connect restaurant orders to kitchen preparation with RESTRA’s kitchen display and order tracking workflow.",intro:"RESTRA connects incoming restaurant orders to kitchen preparation so staff can see what is new, confirmed, preparing, ready, and served.",sections:[{heading:"From order to kitchen",body:"Orders can be sent directly to the kitchen and tracked through a defined lifecycle, helping front-of-house and kitchen teams share the same status.",bullets:["Orders sent directly to the kitchen","New, confirmed, preparing, ready, and served statuses","Live preparation visibility for staff","Order lifecycle visibility for managers"]}]},
{slug:"table-management",title:"Restaurant Table Management",description:"Manage dine-in table activity as part of RESTRA’s restaurant management system.",intro:"RESTRA includes table management capabilities for dine-in operations, with table activity connected to ordering, kitchen status, and billing workflows.",sections:[{heading:"Dine-in operations in one flow",body:"Restaurant staff can use table activity as part of the wider order lifecycle, from a customer’s table order through kitchen preparation and billing.",bullets:["Dine-in order workflows","Table activity visibility","Table management permissions for staff roles","Connected order and billing context"]}]},
{slug:"qr-ordering",title:"QR Ordering for Restaurants",description:"Let restaurant customers scan a QR code, browse a digital menu, and place orders from their phone with RESTRA.",intro:"RESTRA’s QR ordering flow lets customers scan a code at the table, open a digital menu, place an order, and receive order status updates without downloading an app.",sections:[{heading:"How QR ordering works",body:"The customer scans the table QR code, browses the digital menu, selects items, and submits the order. The order is then sent into the restaurant workflow.",bullets:["Scan a QR code at the table","Browse a digital menu on a phone","Place an order without an app download","Send the order to the kitchen","View real-time order status updates"]}]},
{slug:"analytics",title:"Restaurant Analytics and Reporting",description:"Understand restaurant sales, orders, inventory movement, and activity with RESTRA reporting and analytics.",intro:"RESTRA gives restaurant teams an operational view of sales, orders, inventory movement, and overall activity through reports and a live dashboard.",sections:[{heading:"What RESTRA reporting covers",body:"Reports and analytics help managers review the activity that keeps a restaurant running day to day.",bullets:["Sales visibility","Order activity","Inventory movement","Overall restaurant activity","Live dashboard insight"]}]}
];
export const seoPages=Object.fromEntries(pages.map(p=>[p.slug,p])) as Record<string,SeoPage>;
export const featureSlugs=["pos","inventory","kitchen-display-system","table-management","qr-ordering","analytics"];
export const absoluteUrl=(path="")=>`${siteConfig.url}${path}`;
